### PR TITLE
Refactor and add missing translations to clipboard

### LINKED ISSUE #166: Kielikäännösten huomiot
- [x] Käännösten kopiointi exceliin onnistui hyvin. Huomasin kuitenkin, että excelistä puuttui ainakin liukukytkin- ja likert-kysymyksen vaihtoehdot.

- [x] #176

### PR DESCRIPTION
**Pull request by mmoila**
Fixed an issue where all question values for matrix and slider questions would not get copied to clipboard.

Closes #166

### CODE REVIEW

**Review by jpeltzi — CHANGES_REQUESTED** [review]
The verbal descriptions of slider's minimum and maximum values don't seem to appear in neither clipboard nor the translation UI.

**Comment by mmoila** [comment]
> The verbal descriptions of slider's minimum and maximum values don't seem to appear in neither clipboard nor the translation UI.

**Comment by jpeltzi** [comment]
Had a Huddle, some tweaks left to do...

**Review by ossitammi — APPROVED** [review]
LGTM ⭐

**Pull request merged**
